SRegEastTrade          = '\Software\TotalFinance';
SRegServerName         = 'ServerName';
SRegDateFormat         = 'DateFormat';
SRegLongDateFormat     = 'LongDateFormat';
SRuLayout              = '00000419';

SConnectError          = 'Ошибка подключения к серверу базы данных.'#13#10 +
                         'Проверьте логическое имя и пароль.'#13#10#13#10 +
                         '%s';

SDBO                   = 'dbo';

SDateFormatStored      = 'Формат даты-времени установлен';
SErrInvalidDateFormat  = 'Формат даты-времени не установлен.'#13#10'Указано недопустимое значение';

